sudo: false
language: python
cache: pip
python:
- '3.6'
- '3.7'
env:
- DJANGO="django>=2.2,<2.3"
- DJANGO="django>=3.0,<3.1"
before_install:
- pip install codecov
install:
- pip install $DJANGO Sphinx -e .
script:
- coverage run --rcfile=.coveragerc runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: WWNa4MHf50AOybB+XW9UKXCk/9Q8r++Jc4xTdEib43rj4odH9wxIaTRrzAbbpo3EO2gYuLgq6mMbaIZPD5l2UmgSnyuIbeYAAKIQblT+8XMamtXwnSS5j9vfBXYdj54rTlh+jKwEMW/JiQKl+SQpfQ2v1NMvYO63m89Ev9vXvcU=
    on_success: never
    on_failure: always
